languages:
- python


- name: python
  production:
    exclude:
      - /aat/tests/.*
  test:
    include:
      - /aat/tests/.*

exclude:
- /docs/.*
- .*/setup\.py
- /scripts/.*
- /aat/logging\.py
- /aat/define\.py
- /aat/strategies/.*
