languages:
- python


- name: python
  production:
    exclude:
      - /algocoin/tests/.*
  test:
    include:
      - /algocoin/tests/.*

exclude:
- /docs/.*
- .*/setup\.py
- /algocoin/lib/oe/.*
- /algocoin/lib/oe/poloniex/.*
- /scripts/.*
- /algocoin/lib/logging\.py
- /algocoin/lib/define\.py
- /algocoin/custom\_strategies\.py
- /custom_strategies/.*
- /algocoin/lib/strategies/.*
