dist: xenial
language: node_js
node_js: "12"
sudo: required

matrix:
  fast_finish: true
  include:
    # Python 3.7 Linux build - docker
    - python: "3.7"
      language: python
      env: TEST=DOCKER
      cache: pip
      services: docker

    # Python 3.7 Linux build
    - python: "3.7"
      env: TEST=PYTHON
      language: python
      cache: pip

    # Python 3.7 Linux manylinux2010 build
    - python: "3.7"
      language: python
      env: TEST=MANYLINUX2010
      cache: pip
      services: docker

    # Python 3.7 Linux manylinux2014 build
    - python: "3.7"
      language: python
      env: TEST=MANYLINUX2014
      cache: pip
      services: docker

    # Python 3.7 Mac build
    - env: TEST=PYTHON
      cache: pip
      os: osx
      osx_image: xcode11.2

  allow_failures:
    # Mac builds get extensively tested by the core developers.
    # They are also extremely slow to load on travis.
    # So pull requests should check these, but they are allowed
    # to fail

    # Python 3.7 Linux manylinux2014 build
    - python: "3.7"
      language: python
      env: TEST=MANYLINUX2014
      cache: pip
      services: docker

    # Python 3.7 Mac build
    - env: TEST=PYTHON
      cache: pip
      os: osx
      osx_image: xcode11.2

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
  homebrew:
    update: true
    packages:
      - python
      - pybind11
      - cmake


script:
  - if [ "$TEST" = "PYTHON" ]; then python3 -m pip install -e .[dev]; fi
  - if [ "$TEST" = "PYTHON" ]; then make lint; fi
  - if [ "$TEST" = "PYTHON" ]; then make tests; fi
  - if [ "$TEST" = "DOCKER" ]; then docker build .; fi

branches:
  only:
  - master

notifications:
  email: false
